name: Deploy Backend

on:
  push:
    branches:
        - main
    paths:
        - 'apps/backend/**'
        - 'packages/**'
        - 'docker/backend.DockerFile'
        - '.github/workflows/cd_backend.yml'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        # Clones the latest code from the repo
      - uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/backend.DockerFile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/todo-app-backend:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/todo-app-backend:latest 

          ## Steps to deploy to a VM
      - name: SSH into VM and Deploy
        uses: appleboy/ssh-action@v1
        with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            script: |
              sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/todo-app-backend:latest
              sudo docker stop backend || true
              sudo docker rm backend || true
              sudo docker run -d --name backend -p 8080:8080 --restart always -e DATABASE_URL=${{ secrets.DATABASE_URL }} ${{ secrets.DOCKERHUB_USERNAME }}/todo-app-backend:latest
              sudo docker system prune -f 
      

        





